package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"

	"github.com/quitefounder/reliable-commerce-core/api/graph/model"
	"github.com/quitefounder/reliable-commerce-core/api/internal/commerce"
)

// Checkout is the resolver for the checkout field.
func (r *mutationResolver) Checkout(ctx context.Context, input model.CheckoutInput) (*model.Order, error) {
	lines := make([]commerce.LineInput, len(input.Lines))
	for i, l := range input.Lines {
		lines[i] = commerce.LineInput{VariantID: l.VariantID, Quantity: l.Quantity}
	}
	order, err := r.Commerce.Checkout(ctx, commerce.CheckoutInput{
		IdempotencyKey: input.IdempotencyKey,
		Email:          input.Email,
		Lines:          lines,
	})
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapOrder(order), nil
}

// MarkPaid is the resolver for the markPaid field.
func (r *mutationResolver) MarkPaid(ctx context.Context, id string) (*model.Order, error) {
	order, err := r.Commerce.MarkPaid(ctx, id)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapOrder(order), nil
}

// StartPrint is the resolver for the startPrint field.
func (r *mutationResolver) StartPrint(ctx context.Context, id string) (*model.Order, error) {
	order, err := r.Commerce.StartPrint(ctx, id)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapOrder(order), nil
}

// MarkShipped is the resolver for the markShipped field.
func (r *mutationResolver) MarkShipped(ctx context.Context, id string) (*model.Order, error) {
	order, err := r.Commerce.MarkShipped(ctx, id)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapOrder(order), nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, id string) (*model.Order, error) {
	order, err := r.Commerce.Cancel(ctx, id)
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapOrder(order), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	products, err := r.Commerce.Products(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	out := make([]*model.Product, len(products))
	for i, p := range products {
		out[i] = mapProduct(p)
	}
	return out, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	p, err := r.Commerce.Product(ctx, id)
	if errors.Is(err, commerce.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapProduct(*p), nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	o, err := r.Commerce.Order(ctx, id)
	if errors.Is(err, commerce.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, gqlErr(err)
	}
	return mapOrder(o), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
