// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CheckoutInput struct {
	// Caller-supplied key. Replays must send the same payload.
	IdempotencyKey string            `json:"idempotencyKey"`
	Email          string            `json:"email"`
	Lines          []*OrderLineInput `json:"lines"`
}

// Integer money. amountCents is minor units; never a float.
type Money struct {
	AmountCents int    `json:"amountCents"`
	Currency    string `json:"currency"`
}

type Mutation struct {
}

type Order struct {
	ID        string       `json:"id"`
	Status    OrderStatus  `json:"status"`
	Email     string       `json:"email"`
	Lines     []*OrderLine `json:"lines"`
	Total     *Money       `json:"total"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

type OrderLine struct {
	Variant   *Variant `json:"variant"`
	Quantity  int      `json:"quantity"`
	UnitPrice *Money   `json:"unitPrice"`
}

type OrderLineInput struct {
	VariantID string `json:"variantId"`
	Quantity  int    `json:"quantity"`
}

type Product struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Variants    []*Variant `json:"variants"`
}

type Query struct {
}

type Variant struct {
	ID        string `json:"id"`
	Sku       string `json:"sku"`
	Size      string `json:"size"`
	Finish    string `json:"finish"`
	UnitPrice *Money `json:"unitPrice"`
	// Units checkout may still take: on_hand − reserved.
	Available int `json:"available"`
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "PENDING"
	OrderStatusPaid      OrderStatus = "PAID"
	OrderStatusPrinting  OrderStatus = "PRINTING"
	OrderStatusShipped   OrderStatus = "SHIPPED"
	OrderStatusCancelled OrderStatus = "CANCELLED"
)

var AllOrderStatus = []OrderStatus{
	OrderStatusPending,
	OrderStatusPaid,
	OrderStatusPrinting,
	OrderStatusShipped,
	OrderStatusCancelled,
}

func (e OrderStatus) IsValid() bool {
	switch e {
	case OrderStatusPending, OrderStatusPaid, OrderStatusPrinting, OrderStatusShipped, OrderStatusCancelled:
		return true
	}
	return false
}

func (e OrderStatus) String() string {
	return string(e)
}

func (e *OrderStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderStatus", str)
	}
	return nil
}

func (e OrderStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
